development:
  adapter: async

test:
  adapter: async

# production:
  # adapter: redis
  # url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/1' %>
  # url: redis://localhost:6379/1

production: &production
  :url: redis://redistogo:2c4f0dade8d04ae437dac5fab47aae32@koi.redistogo.com:9792/
  :host: koi.redistogo.com
  :port: 9792
  :password: 2c4f0dade8d04ae437dac5fab47aae32
  :inline: true
  :timeout: 1
